# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-05-23 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('summary', models.CharField(max_length=512)),
                ('a_url', models.URLField()),
                ('img_url', models.URLField()),
                ('tags', models.CharField(max_length=128)),
            ],
        ),
    ]
